"""empty message

Revision ID: dda4574834d1
Revises: 0c6979e49f7b
Create Date: 2017-12-28 18:12:46.866108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda4574834d1'
down_revision = '0c6979e49f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.add_column('eventlists', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'eventlists', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'eventlists', type_='foreignkey')
    op.drop_column('eventlists', 'created_by')
    op.drop_table('users')
    # ### end Alembic commands ###
